config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :friends
  #get 'home/index'
  root 'home#index'
  get 'home/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/friend.rb
class Friend < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :friends
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/friends_controller.rb
class FriendsController < ApplicationController
  before_action :set_friend, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]  
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /friends or /friends.json
  def index
    @friends = Friend.all
  end

  # GET /friends/1 or /friends/1.json
  def show
  end

  # GET /friends/new
  def new
    #@friend = Friend.new
    @friend = current_user.friends.build
  end

  # GET /friends/1/edit
  def edit
  end

  # POST /friends or /friends.json
  def create
    #@friend = Friend.new(friend_params)
    @friend = current_user.friends.build(friend_params)

    respond_to do |format|
      if @friend.save
        format.html { redirect_to @friend, notice: "Friend was successfully created." }
        format.json { render :show, status: :created, location: @friend }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /friends/1 or /friends/1.json
  def update
    respond_to do |format|
      if @friend.update(friend_params)
        format.html { redirect_to @friend, notice: "Friend was successfully updated." }
        format.json { render :show, status: :ok, location: @friend }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @friend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /friends/1 or /friends/1.json
  def destroy
    @friend.destroy
    respond_to do |format|
      format.html { redirect_to friends_url, notice: "Friend was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  #check for authorized useer
  def correct_user
    @friend = current_user.friends.find_by(id: params[:id])
    redirect_to friends_path, notice: "Unauthorized User" if @friend.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_friend
      @friend = Friend.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def friend_params
      params.require(:friend).permit(:first_name, :last_name, :email, :phone, :twitter, :user_id)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  	@about_me = "My Name is Biplav Raj Raut."
  	@answer = 2 + 2
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/friends_helper.rb
module FriendsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/friends/_form.html.erb
<%= form_with(model: friend) do |form| %>
  <% if friend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(friend.errors.count, "error") %> prohibited this friend from being saved:</h2>

      <ul>
        <% friend.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, class:"form-control", placeholder:"John" %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, class:"form-control", placeholder:"Doe"  %>
  </div>

  <div class="field form-group">
    <%= form.label :email %>
    <%= form.text_field :email, class:"form-control", placeholder:"example@abc.com"  %>
  </div>

  <div class="field form-group">
    <%= form.label :phone %>
    <%= form.text_field :phone, class:"form-control", placeholder:"98********"  %>
  </div>

  <div class="field form-group">
    <%= form.label :twitter %>
    <%= form.text_field :twitter, class:"form-control", placeholder:"@twitter"  %>
  </div>
  <div class="field form-group">
    <%= form.number_field :user_id, id: :friend_user_id, class:"form-control", value:current_user.id, type:"hidden"  %>
  </div>
  <div class="actions mt-3">
    <%= form.submit class:"btn btn-primary" %>
  </div>
  <br>
<% end %>

app/views/friends/edit.html.erb
<h1>Editing Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Show', @friend, class:"btn btn-success" %> |
<%= link_to 'Destroy', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> |
<%= link_to 'Back', friends_path,class:"btn btn-secondary" %>

app/views/friends/index.html.erb
<h1>Friends List</h1>

<table class="table table-striped">
  <thead class="table-dark">
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Twitter</th>
      <th>User</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @friends.each do |friend| %>
      <tr>
        <td><%= link_to friend.first_name + ' ' + friend.last_name, friend %></td>
        <td><%= friend.email %></td>
        <td><%= friend.phone %></td>
        <td><%= friend.twitter %></td>
        <td><%= friend.user_id %></td>
        <% if friend.user == current_user %>
          <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger" %></td>
        <% else %>
          <td><%= link_to 'Destroy', friend, method: :delete, data: { confirm: 'Unauthorized User.' }, class:"btn btn-sm btn-outline-danger" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Friend', new_friend_path, class: "btn btn-primary" %>

app/views/friends/new.html.erb
<h1>Add New Friend</h1>

<%= render 'form', friend: @friend %>

<%= link_to 'Back', friends_path, class:"btn btn-secondary" %>

app/views/friends/show.html.erb
<div class="card" style="width: 100%;">
  <div class="card-header">
    <strong> Hello, <%= @friend.first_name %></strong>
  </div>
  <ul class="list-group list-group-flush">
    <li class="list-group-item"><strong>First name:</strong>
      <%= @friend.first_name %>
    </li>
    <li class="list-group-item"><strong>Last name:</strong>
      <%= @friend.last_name %>
    </li>
    <li class="list-group-item"><strong>Email:</strong>
      <%= @friend.email %>
    </li>
    <li class="list-group-item"><strong>Phone:</strong>
      <%= @friend.phone %>
    </li>
    <li class="list-group-item"><strong>Twitter:</strong>
      <%= @friend.twitter %>
    </li>
  </ul>
  <div class="card-footer">
    <%= link_to 'Edit', edit_friend_path(@friend), class:"btn btn-success" %> |
    <%= link_to 'Destroy', @friend, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger" %> |
    <%= link_to 'Back', friends_path, class:"btn btn-secondary" %>
  </div>
</div>

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  	<%= link_to 'ROR App', root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
        	<%= link_to 'Home', root_path, class: "nav-link active" %>
        </li>
        <li class="nav-item">
        	<%= link_to 'About Us', home_about_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        	<%= link_to 'Friends', friends_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
	        <li class="nav-item">
	        	<%= link_to 'New Friends', new_friend_path, class: "nav-link" %>
	        </li>
        <% end %>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            User
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          	<li><a class="dropdown-item" href="#">Something else here</a></li>
          	<li><hr class="dropdown-divider"></li>
          	<% if user_signed_in? %>
	          	<li>
		        	<%= link_to 'Sign Out',  destroy_user_session_path, method: :delete, class: "dropdown-item" %>
		        </li>
		        <li>
		        	<%= link_to 'Edit Profile', edit_user_registration_path, class: "dropdown-item" %>
		        </li>  
		        <% else %>
	          	<li>
		        	<%= link_to 'Sign Up', new_user_registration_path, class: "dropdown-item" %>
		        </li>
		        <li>
		        	<%= link_to 'Sign In', new_user_session_path, class: "dropdown-item" %>
		        </li>
	        <% end %>
	                 
            
          </ul>
        </li>
      </ul>
      <form class="d-flex">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>
<p><%= @about_me %></p>
<p><%= @answer %></p>

app/views/home/index.html.erb
<h1>Hello world</h1>
<p>This is first webpage.</p>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
	<%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>Friends</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous">

  </head>
  <body>
    <%= render "home/header" %>
    <div class="container" style="margin-top: 20px;">
    <% if notice %>
      <%= render "layouts/alerts" %>
    <% end %>
      <%= yield %>
    </div>

    <!-- Optional JavaScript; choose one of the two! -->

    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>

    <!-- Option 2: Separate Popper and Bootstrap JS -->
    <!--
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.min.js" integrity="sha384-lpyLfhYuitXl2zRZ5Bn2fqnhNAKOAaM/0Kr9laMspuaMiZfGmfwRNFh8HlMy49eQ" crossorigin="anonymous"></script>
    -->
  </body>
</html>